#!/bin/sh
mocha test/getTLIdEncoderDecoder.js
mocha test/manip.js
mocha test/Path/AsyncLocalStorage.js
mocha test/ServerPersist/MemoryAsync.js
mocha test/SyncIt.js
mocha test/SyncItTestServ.js
mocha test/SyncLocalStorage.js
mocha test/Unsupported/DojoTest.js
mocha test/updateResult.js
