#!/bin/sh

## Author: Matthew Forrester <matt_at_keyboardwritescode.com>
## Copyright: Matthew Forrester·
## License: MIT/BSD-style·

if [ $# -ne 2 ]
then
  echo "Downloads an archive from GitHub and stores the contents of a subdirector in a"
  echo "local path."
  echo ""
  echo "Usage: extract_github_archive [GITHUB_MASTER_DOWNLOAD] [DESTINATION_DIRECTORY]"
  exit 1
fi

DIRNAME="/tmp/extract_github_archive-$(date +%s)"
DEST=$2
wget -q $1 -O ${DIRNAME}.zip
unzip -qq ${DIRNAME}.zip -d $DIRNAME
MAIN_DIR=`ls $DIRNAME | head -1`
if [ ! -d $DEST ]; then
	mkdir -p $DEST
fi
tar -c -C $DIRNAME/$MAIN_DIR . | tar -x -C $DEST
rm ${DIRNAME}.zip
rm -rf ${DIRNAME}
